document.getElementById('slot-s10').outerHTML = `  <section id="s10" class="section">
    <div class="section-eyebrow">Section 10</div>
    <h1 class="section-title">World Zones</h1>

    <div class="card-grid">
      <div class="card">
        <span class="card-icon">🏚️</span>
        <div class="card-title">Zone 1 — Dustfall Slums</div>
        <p><strong>Biome:</strong> Vertical ruin-city. Former Mumbai. 80% below the sandline.<br><strong>Tone:</strong> Desperate, alive, maze-like.<br><strong>Threats:</strong> Low-tier mineral fauna, gang territory, sand sinkholes.<br><strong>Story Role:</strong> Tutorial zone. Kai's home. All factions present at reduced capacity.</p>
      </div>
      <div class="card crystal">
        <span class="card-icon">🌅</span>
        <div class="card-title">Zone 2 — The Glass Wastes</div>
        <p><strong>Biome:</strong> Open desert. Sand fused into irregular glass plains.<br><strong>Tone:</strong> Beautiful, deadly, exposed.<br><strong>Threats:</strong> Open-world boss events, sand predators, Hollowed raids.<br><strong>Story Role:</strong> Act II main zone. Faction territory wars visible in real time.</p>
      </div>
      <div class="card danger">
        <span class="card-icon">🕳️</span>
        <div class="card-title">Zone 3 — The Subterrane</div>
        <p><strong>Biome:</strong> Underground dungeon network. Shifting, unstable.<br><strong>Tone:</strong> Claustrophobic, disorienting, lore-dense.<br><strong>Threats:</strong> Most dangerous non-boss enemies. Maximum dungeon instability.<br><strong>Story Role:</strong> Act III primary zone. The Resonance Order Archives are here.</p>
      </div>
      <div class="card green">
        <span class="card-icon">🌿</span>
        <div class="card-title">Zone 4 — The Cryssal Canopy</div>
        <p><strong>Biome:</strong> Former rainforest, fully crystallized. Trees of glass, crystal birds.<br><strong>Tone:</strong> Eerie beauty. Like a museum of the old world.<br><strong>Threats:</strong> Crystallized wildlife, particularly aggressive fauna.<br><strong>Story Role:</strong> Act II–III bridge. The Echo Wardens' hidden base is here.</p>
      </div>
      <div class="card">
        <span class="card-icon">🌊</span>
        <div class="card-title">Zone 5 — The Dune Seas</div>
        <p><strong>Biome:</strong> Vast open dune ocean. Former Mediterranean basin.<br><strong>Tone:</strong> Epic scale. Wind-carved silica formations. Sky is permanently amber.<br><strong>Threats:</strong> Dune predators, rival Silt Runner bands, sandstorm events.<br><strong>Story Role:</strong> Open-world hub between Acts. Main traversal via Dune Surfing.</p>
      </div>
      <div class="card danger">
        <span class="card-icon">🗿</span>
        <div class="card-title">Zone 6 — The Obelisk Approach</div>
        <p><strong>Biome:</strong> Reality fracture zone. Geometry unstable. Massive Nullite crystal formations.<br><strong>Tone:</strong> Overwhelming. The sky is wrong. Sound is wrong. Colors bleed.<br><strong>Threats:</strong> The Obelisk's direct immune response units. Nearly unbeatable by standard means.<br><strong>Story Role:</strong> Act IV only. Final zone. No return after entering.</p>
      </div>
    </div>

    <h2>Dungeon Design Philosophy</h2>
    <p>Dungeons are <strong>wounds in reality</strong> — areas where the conversion process is incomplete and chaotic. No dungeon map is static across visits. Two core dungeon types exist:</p>
    <div class="two-col">
      <div>
        <h3>Scar Dungeons</h3>
        <p>Partially collapsed structures mid-conversion. Relatively predictable layout with random room arrangements each entry. Rich in minerals, high enemy density, one guaranteed boss room.</p>
      </div>
      <div>
        <h3>Hollow Vaults</h3>
        <p>Fully generated by the Obelisk as defense structures. Geometry actively shifts during exploration. Contains Echo memory deposits tied to major lore. Highest risk, highest reward. Some rooms only accessible during low-corruption runs.</p>
      </div>
    </div>
  </section>`;
